<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="EBIDM">
      <HintPath>..\SenangRetails.Shared\EBIDM.dll</HintPath>
    </Reference>
    <Reference Include="EBIEF">
      <HintPath>..\SenangRetails.Shared\EBIEF.dll</HintPath>
    </Reference>
    <Reference Include="EBIEnum">
      <HintPath>..\SenangRetails.Shared\EBIEnum.dll</HintPath>
    </Reference>
    <Reference Include="EBIUC">
      <HintPath>..\SenangRetails.Shared\EBIUC.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SenangRetails.Shared\SenangRetails.Shared.csproj" />
  </ItemGroup>

</Project>
